apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-08T03:31:36Z"
  labels:
    run: redis
  name: redis
  namespace: default
  resourceVersion: "42121"
  selfLink: /api/v1/namespaces/default/services/redis
  uid: 4230481a-4046-4e23-8c39-fbcbf7788aed
spec:
  clusterIP: 10.111.152.199
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31326
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: redis
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
