apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-web
  labels:
    app: study-web
spec:
  replicas: 1
  template:
    metadata:
      name: study-web
      labels:
        app: study-web
    spec:
      containers:
      - name: study-web
        image: 192.168.10.198:5000/chengweiping/study-web:0.0.1
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: study-web
