apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-13T04:27:45Z"
  labels:
    app: study-web
  name: study-web
  namespace: default
  resourceVersion: "104145"
  selfLink: /api/v1/namespaces/default/services/study-web
  uid: daa9dc2c-8cc0-4281-b589-d85139e816dc
spec:
  clusterIP: 10.109.118.241
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31331
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: study-web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
