apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-08T02:38:57Z"
  labels:
    run: mysql
  name: mysql
  namespace: default
  resourceVersion: "38290"
  selfLink: /api/v1/namespaces/default/services/mysql
  uid: 61265733-f41c-4c66-986d-ae5027cdf76e
spec:
  clusterIP: 10.111.169.218
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31586
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
