image: docker:latest  #1
variables:  #2
  DOCKER_DRIVER: overlay2
#  DOCKER_HOST: tcp://127.0.0.1:2375  # docker host，本地可不写
  TAG: 127.0.0.1:5000/chengweiping/study-web:1.0.0 # 镜像名称
cache:  #3
  paths:
    - .m2/repository
services:  #4
  - docker:dind
stages:  #5
  - package
  - deploy
maven-package:  #6
  image: maven:3.5-jdk-8-alpine
  tags:
    - maven
  stage: package
  script:
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - study-web/target/*.jar
build-master:  #7
  tags:
    - docker
  stage: deploy
  script:
    - docker build -t $TAG .
   # - docker rm -f test || true
   # - docker run -d --name test -p 5000:5000 $TAG
  only:
    - master