apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: maual
  capacity:
    storage: 120M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/E/01docker/share/mysql/data"
